spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://47.99.201.124:3306/stj
# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.stj.business.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID", 2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID"
    id-type: 0
    # 字段策略 0:"忽略判断", 1:"非 NULL 判断"), 2:"非空判断"
    field-strategy: 2
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
# logback
logging:
  level:
    org.springframework.web: INFO
    com.stj.business.mapper: INFO
stj:
  # swagger
  swagger:
    enable: true
    base-package: com.stj.business.api.impl,com.stj.wechat.api.impl
    title: 山田尖电商平台
    description: api接口信息
    version: 1.0
  proxy:
    charset: utf_8
    host: 10.1.27.102
    enable-proxy: false
    ssh-check: false
  # wechat
  wechat:
    app-id: wx73770f8f029e1b50
    appsecret: 7afde07a322e7c33bc5e0fbdd340ec28
    # app-id: wx5383e6f83af389db
    # appsecret: 3f5ebfc3e911afdda58ed70823819398
    open-app-id: wxc72866875cad5fe1
    open-appsecret: 8ba97e7f0ed649472718d1f4abaef62d
  # 跨域设置
  cross:
    api-white-list: /swagger-resources/**,/webjars/**,/null/swagger-resources/**,
                    /swagger-ui.html,/error,/v2/api-docs,/auth/sign
