server:
  port: 27000
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://172.16.131.42:3306/sjt?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
# logback
logging:
  level:
    org.springframework.web: INFO
    com.sjt.business.mapper: INFO
sjt:
  cross:
    origin: '*'
  # swagger
  swagger:
    title: 'Swagger api 管理平台'
    enable: true
  # 微信(操作 sjt@123456)
  wechat:
    app-id: wx73770f8f029e1b50
    appsecret: 7afde07a322e7c33bc5e0fbdd340ec28
    open-app-id: wxc72866875cad5fe1
    open-appsecret: 8ba97e7f0ed649472718d1f4abaef62d
    applet-id: wx221fcafef33f2b87
    applet-appsecret: e13e84260a7915c690525f671c00ab72
    mch-id: 1543508991
    mch-secret: ZOWWRiOSxly8gtgZE9aNWFrwp8taV4wP
    notifyUrl: http://www.smallbug.top/sjt/wx/pay/open-api/notify

