spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: XiaoLong@510
    url: jdbc:mysql://127.0.0.1:3306/sjt?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
# logback
logging:
  level:
    org.springframework.web: INFO
    com.sjt.business.mapper: INFO
sjt:
  # swagger
  swagger:
    enable: true
  proxy:
    charset: utf_8
    host: 10.1.27.102
    enable-proxy: true
  # 微信
  wechat:
    app-id: wx73770f8f029e1b50
    appsecret: 7afde07a322e7c33bc5e0fbdd340ec28
    open-app-id: wxc72866875cad5fe1
    open-appsecret: 8ba97e7f0ed649472718d1f4abaef62d
    applet-id: wx221fcafef33f2b87
    applet-appsecret: e13e84260a7915c690525f671c00ab72
    applet-mch-id: 1543508991
#    applet-id: wxd46d12c41a64720f
#    applet-appsecret: f73b6b99027c6232307a503336087d2c
